### Introducción a los Arrays

Un **array** es una estructura de datos que nos permite almacenar múltiples valores del mismo tipo en una única variable. En Python, los arrays no son nativos, pero podemos usarlos utilizando la biblioteca `NumPy`.

#### Diferencias con otras estructuras:
- **Listas**: En Python, las listas pueden contener elementos de diferentes tipos y su tamaño es dinámico (pueden crecer o disminuir).
- **Tuplas**: Como las listas, pueden contener diferentes tipos, pero su tamaño es fijo y no pueden ser modificadas.
- **Arrays**: Solo pueden contener un tipo de dato y, a menudo, tienen un tamaño fijo. Esto los hace más eficientes en términos de acceso y manipulación.

Un array es útil cuando queremos trabajar con grandes cantidades de datos homogéneos, especialmente para cálculos numéricos.

---

### Instalación de NumPy

Antes de trabajar con arrays, necesitamos instalar la biblioteca `NumPy`, que es la más popular para el trabajo con arrays en Python. Para instalarla, ejecuta lo siguiente en tu terminal:

```bash
pip install numpy
```

---

### Creación de Arrays

Para crear un array con NumPy, primero tenemos que importar la biblioteca:

In [1]:
import numpy as np

#### Crear un array a partir de una lista

Imagina que tienes una lista de números y quieres convertirla en un array:

In [3]:
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)

[1 2 3 4 5]


#### Crear arrays con valores predefinidos

NumPy nos ofrece varias funciones útiles para crear arrays rápidamente con valores específicos:


In [2]:
# Zeros: Crea un array lleno de ceros.
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [4]:
# Ones: Crea un array lleno de unos.
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Range: Crea un array con un rango de valores.
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# Linspace: Crea un array con números espaciados uniformemente.
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


### Accediendo a Elementos de un Array

El acceso a los elementos en un array es muy similar a cómo accedemos a los elementos en una lista.

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])

10
50


Para arrays multidimensionales, utilizamos índices separados por comas.

In [8]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0, 1])
print(arr2d[2, 2])

2
9


### Operaciones Básicas con Arrays

Uno de los beneficios principales de los arrays es que nos permiten realizar operaciones matemáticas de manera muy eficiente:

**Suma de arrays**: La suma se realiza elemento por elemento.

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


**Multiplicación por un escalar**: Puedes multiplicar todos los elementos por un número.

In [10]:
print(a * 2)

[2 4 6]


**Exponenciación**: También puedes elevar los elementos de un array a una potencia.

In [11]:
print(a ** 2)

[1 4 9]


### Beneficios de Usar Arrays en NumPy

Los arrays de NumPy son más rápidos y eficientes que las listas regulares, especialmente cuando se realizan operaciones con grandes conjuntos de datos. NumPy está optimizado para realizar cálculos numéricos complejos y es ampliamente utilizado en **ciencia de datos**, **análisis numérico**, y **aprendizaje automático**.

### Slicing (Corte) de Arrays

El **slicing** es una técnica muy útil que nos permite acceder a subconjuntos de un array. Esto es similar a cómo cortamos listas en Python, pero con arrays de NumPy también podemos hacer slicing en múltiples dimensiones.

#### Slicing en Arrays Unidimensionales

Con los arrays de una sola dimensión, el slicing funciona igual que con las listas. Usamos los índices para seleccionar una porción del array:

In [12]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Seleccionar los elementos de la posición 2 a la 4
sub_array = arr[2:5]
print(sub_array)

[30 40 50]


También podemos modificar elementos directamente mediante slicing:

In [13]:
arr[2:5] = 100
print(arr)

[ 10  20 100 100 100  60]


#### Slicing en Arrays Multidimensionales

Cuando trabajamos con arrays de más de una dimensión, podemos hacer slicing en cada dimensión usando comas para separar los índices.

Imagina que tenemos una matriz 3x3:

In [14]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [15]:
# Seleccionar la submatriz de las primeras dos filas y las primeras dos columnas
sub_array = arr2d[:2, :2]
print(sub_array)

[[1 2]
 [4 5]]


#### Combinación de Índices y Slices

También es posible combinar la selección de un índice específico con slicing en otra dimensión:

In [16]:
# Seleccionamos la primera fila completa
fila = arr2d[0, :]
print(fila)  # Salida: [1 2 3]

[1 2 3]


In [17]:
# Seleccionamos la primera columna completa
columna = arr2d[:, 0]
print(columna)  # Salida: [1 4 7]

[1 4 7]


### Mutabilidad y Vistas

Cuando haces slicing en NumPy, no se crea una copia del array original. En su lugar, obtienes una **vista** del array, lo que significa que si modificas la vista, también estarás modificando el array original.


In [18]:
arr = np.array([1, 2, 3, 4, 5])
sub_array = arr[1:4]
sub_array[:] = 100
print(arr)

[  1 100 100 100   5]


Si no quieres que los cambios afecten el array original, puedes usar el método `copy()` para crear una copia independiente.


In [19]:
sub_array = arr[1:4].copy()
sub_array[:] = 200
print(arr)

[  1 100 100 100   5]


### Operaciones Avanzadas con Arrays

Ahora que tenemos una buena comprensión de los conceptos básicos, vamos a explorar algunas operaciones más avanzadas que podemos hacer con arrays en NumPy.



#### Operaciones Vectorizadas

Una de las razones por las que NumPy es tan poderoso es que permite realizar operaciones sobre arrays completos sin necesidad de usar bucles. Esto se conoce como **operaciones vectorizadas** y es lo que hace que NumPy sea tan rápido.

In [20]:
# supongamos que queremos sumar dos arrays:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma elemento por elemento
suma = a + b
print(suma)

[5 7 9]


La ventaja de las operaciones vectorizadas es que son más rápidas y concisas que los bucles tradicionales.

#### Funciones Universales (ufuncs)

NumPy tiene un conjunto de **funciones universales** que nos permiten realizar operaciones matemáticas directamente en arrays. Algunas de las funciones más comunes son:

- `np.sqrt()`: Raíz cuadrada de cada elemento.
- `np.exp()`: Exponencial de cada elemento.
- `np.sin()`, `np.cos()`: Funciones trigonométricas.
- `np.log()`: Logaritmo natural.

In [ ]:
# Ejemplo:
arr = np.array([1, 4, 9, 16])

raiz_cuadrada = np.sqrt(arr)
print(raiz_cuadrada)

### Cambiar la Forma de un Array

NumPy te permite cambiar la forma (dimensiones) de un array sin modificar sus datos, lo que es especialmente útil cuando trabajas con arrays multidimensionales.

#### `reshape()`
Con `reshape()`, podemos cambiar la forma de un array. Por ejemplo, convertir un array de 1D a 2D:

In [21]:
arr = np.arange(6)
arr_2d = arr.reshape((2, 3))
print(arr_2d)

[[0 1 2]
 [3 4 5]]


#### `ravel()` y `flatten()`

Si queremos aplanar un array multidimensional de vuelta a 1D, podemos usar `ravel()` o `flatten()`:

- `ravel()` devuelve una vista del array original (sin copiar los datos).
- `flatten()` crea una copia independiente del array.

In [22]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = arr_2d.ravel()
print(arr_1d)

[1 2 3 4 5 6]
